### ISSUE TITLE
Is there a way to rollback the database change if the persister fails to save to the audit log?

### ISSUE THREAD

**Issue by aceat64** [lorenzo/audit-stash#22]
I've had some issues with an elasticsearch cluster that's less than 100% uptime, it would be nice to have the database modifications rollback or fail, if the persister is unable to write an audit log entry. Any suggestions for accomplishing this?

**Comment by lorenzo** [comment]
Currently the listener is setup to work in `afterSaveCommit`, so the changes are already persisted and it is too late to roll them back. A few ideas:

* Use a queue persister. Instead of writing directly to a datasource, write to a queue and consume later. This way you can solve the persistence error in the queue and not lose the audits.
* Use a composite persister for better failover. Create a persister that tries to save directly, if it fails, write to a queue, if it fails write to disk (or log)
* Use database savepoints (I don't have a clear idea how this would work)

I'm closing the issue since this was just a question.
